### ISSUE TITLE
AutoTyper paranthesis don't work

### ISSUE THREAD

**Issue by MiscrosoftIsStupid** [Parveshdhull/AutoTyper#4]
Hello! I've been attempting to use this software to type parts of this program I'm creating but it cannot type parenthesis, are there any fixes?

**Comment by Parveshdhull** [comment]
what issue you are facing? it is working for me

https://drive.google.com/file/d/1mKPDbbqZ6XJRiODKDvpsr3hBSTCypPfV/view?usp=sharing

**Comment by MiscrosoftIsStupid** [comment]
When having the autotyper type something like "print('Hello World!')" it
prints "print'Hello World!'".

**Comment by Parveshdhull** [comment]
> "print('Hello World!')"

this also worked for me. Can you please send more info (OS etc.) perhaps with video.

Also, this software mostly targets users which want to use it for data entry like softwares which don't allow copy paste. For your use case, I think better choices will be [autokey ](https://github.com/autokey/autokey) or [xdotool](https://github.com/jordansissel/xdotool)
