### ISSUE TITLE
Symbol "<" changing to ">"

### ISSUE THREAD

**Issue by slaygun** [Parveshdhull/AutoTyper#6]
When I use the autotyper to autotype code if there is "<" present it changes it to ">" after autotyping is done. I m using this on Ubuntu 22.04 lts

**Comment by Parveshdhull** [comment]
Hi @slaygun, Thank you for reporting this issue.

AutoTyper just uses pyautogui for simulating key presses. Looks like this is a [known bug](https://github.com/asweigart/pyautogui/issues/198) in the library.

But it is quite old (reported in 2017), so might not be fixed. Still, you can try the solution provided in the [comment](https://github.com/asweigart/pyautogui/issues/198#issuecomment-1465268536).
